name: Auto PR Generator
on:
  schedule:
    - cron: "0 * * * *"   # Weekdays 9 AM to 5 PM, excluding Sunday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # - name: Random delay
      #   run: |
      #     # Random delay between 30 minutes and 4 hours
      #     delay_minutes=$((RANDOM % 210 + 30))
      #     echo "Waiting $delay_minutes minutes before creating PR..."
      #     sleep $((delay_minutes * 60))
      - name: Make changes to pull request
        run: |
          echo "Update at $(date)" >> DUMMY.md

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: "chore: auto update $(date)"
          committer: le0623 <leonel.lasso210@gmail.com>
          author: le0623 <leonel.lasso210@gmail.com>
          branch: auto-pr
          base: main
          title: "chore: auto update"
          body: "Automated PR to keep activity going"
          delete-branch: true

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
